import type { NextPage } from "next";
import Head from "next/head";
import React, { useState, SetStateAction } from "react";
import { TagButtonType, TagButton, TagList } from "../components/Tags";

const Write: NextPage = () => {
  const [sectionIdx, setSectionIdx] = useState<number>(0);
  return (
    <div>
      <Head>
        <title>Blog Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mt-10">
          <div className="inline-block">
            <h1 className="text-4xl font-bold">태그</h1>
            <p className="text-xl mt-3">
              글의 주제에 맞는 태그를 설정해 주세요!
            </p>
          </div>
        </div>
        <div className="subjects mt-4">
          <div className="flex items-center">
            {TagList.map((menu, idx) => (
              <TagButton
                name={menu}
                mapIdx={idx}
                sectionIdx={sectionIdx}
                setSectionIdx={setSectionIdx}
                key={idx}
              />
            ))}
          </div>
        </div>
        <form className="searchbar mt-10">
          <div className="inline-block">
            <h1 className="text-4xl font-bold">제목</h1>
          </div>
          <div className="relative mt-4">
            <input
              className="block p-4 pl-6 w-full text-base text-black bg-white rounded-xl outline-none"
              placeholder="멋있는 글제목"
            />
          </div>
        </form>
        <div className="mt-10">
          <div className="inline-block">
            <h1 className="text-4xl font-bold">본문</h1>
            <p className="text-xl mt-3">
              본문은 MarkDown 형식으로 작성해 주세요!
            </p>
          </div>
        </div>
      </main>
      {
        // Markdown Editor goes here
      }
      <div className="mt-10">
        <button className="bg-button hover:bg-white hover:text-black font-bold w-40 py-2 px-4 rounded-full sm:float-right flex justify-center">
          등록하기
        </button>
      </div>
    </div>
  );
};

export default Write;
